export interface Review {
  id: string;
  name: string;
  city: string;
  visa: string;
  date: string;
  rating: number;
  text: string;
  lang: "ru" | "en";
}

export const landingReviews: Review[] = [
  {
    id: "1",
    name: "Алексей К.",
    city: "Москва",
    visa: "DTV под ключ",
    date: "18 января 2025",
    rating: 5,
    lang: "ru",
    text: "Сами подавали DTV: отказ. ThaiPass пересобрали пакет, через 11 дней виза была. Писали в Telegram, без воды и лишних обещаний.",
  },
  {
    id: "2",
    name: "Марина С.",
    city: "Санкт-Петербург",
    visa: "Срочная туристическая",
    date: "3 февраля 2025",
    rating: 5,
    lang: "ru",
    text: "Вылет через 5 дней, билеты уже куплены. Успели оформить TR, курьер привёз в Питер. Спокойно, по шагам.",
  },
  {
    id: "3",
    name: "Dmitry V.",
    city: "Moscow",
    visa: "DTV 5 years",
    date: "22 December 2024",
    rating: 5,
    lang: "en",
    text: "Remote worker, applied from Moscow. Clear checklist, no surprises on the bank statement. Got approved on the second review round.",
  },
  {
    id: "4",
    name: "Ольга Н.",
    city: "Казань",
    visa: "Пенсионная 50+",
    date: "9 марта 2025",
    rating: 5,
    lang: "ru",
    text: "Маме 58, переживали за выписку и переводы. Разобрали кейс бесплатно, потом вели до получения. Всё по делу.",
  },
  {
    id: "5",
    name: "Игорь П.",
    city: "Новосибирск",
    visa: "Проверка DTV",
    date: "14 ноября 2024",
    rating: 5,
    lang: "ru",
    text: "Взяли только проверку: сэкономили на повторной подаче. Нашли три ошибки в договоре и фото, которые мы бы пропустили.",
  },
  {
    id: "6",
    name: "Anna L.",
    city: "Bangkok",
    visa: "Tourist TR",
    date: "5 January 2025",
    rating: 5,
    lang: "en",
    text: "Needed TR while already in Thailand planning. They explained consulate timing honestly and helped with document wording.",
  },
  {
    id: "7",
    name: "Светлана Д.",
    city: "Екатеринбург",
    visa: "Туристическая 60+30",
    date: "27 декабря 2024",
    rating: 5,
    lang: "ru",
    text: "Первый раз визу в Таиланд делали через агентство: путаница. Здесь всё в одном чате: что сдать, когда ждать, куда ехать.",
  },
  {
    id: "8",
    name: "Роман Т.",
    city: "Краснодар",
    visa: "Мультивиза 6 мес.",
    date: "11 февраля 2025",
    rating: 5,
    lang: "ru",
    text: "Нужна была мультивиза под частые перелёты. Подсказали по выписке и срокам хранения средств: одобрили с первого раза.",
  },
  {
    id: "9",
    name: "Елена В.",
    city: "Сочи",
    visa: "Перевод документов",
    date: "6 января 2025",
    rating: 5,
    lang: "ru",
    text: "Переводили свидетельство и согласие на выезд ребёнка. Сделали быстро, консульство приняло без вопросов.",
  },
  {
    id: "10",
    name: "Павел М.",
    city: "Воронеж",
    visa: "Бизнес Non-B",
    date: "19 октября 2024",
    rating: 4,
    lang: "ru",
    text: "Non-B для переговоров с партнёром в Бангкоке. Долго согласовывали пакет с работодателя, но в итоге виза пришла в срок.",
  },
  {
    id: "11",
    name: "Julia R.",
    city: "Phuket",
    visa: "DTV documents",
    date: "2 March 2025",
    rating: 5,
    lang: "en",
    text: "Submitted docs myself after their audit. Felt like having a strict editor for my visa folder: worth every ruble.",
  },
  {
    id: "12",
    name: "Наталья Г.",
    city: "Тюмень",
    visa: "DTV под ключ",
    date: "24 февраля 2025",
    rating: 5,
    lang: "ru",
    text: "Живём в регионе: документы отправили курьером. Не пришлось лететь в Москву дважды. Статус визы скидывали в WhatsApp.",
  },
  {
    id: "13",
    name: "Кирилл А.",
    city: "Москва",
    visa: "Срочная туристическая",
    date: "15 декабря 2024",
    rating: 5,
    lang: "ru",
    text: "Ситуация авральная, отвечали вечером в субботу. Честно сказали, что успеваем, и не продавали лишние услуги.",
  },
  {
    id: "14",
    name: "Victor H.",
    city: "Berlin",
    visa: "DTV check",
    date: "8 January 2025",
    rating: 5,
    lang: "en",
    text: "Russian passport, applying from EU. They clarified which income proofs work for DTV soft-power track. Straightforward.",
  },
  {
    id: "15",
    name: "Татьяна Л.",
    city: "Самара",
    visa: "Пенсионная 50+",
    date: "30 января 2025",
    rating: 5,
    lang: "ru",
    text: "С мужем оформляли пенсионную. Помогли с финансовой частью и списком для 90-day report: без паники.",
  },
  {
    id: "16",
    name: "Артём З.",
    city: "Ростов-на-Дону",
    visa: "Туристическая 60+30",
    date: "17 ноября 2024",
    rating: 5,
    lang: "ru",
    text: "Думали, безвиза хватит: не хватило. Переоформили на TR, объяснили разницу нормальным языком, не как в форумах.",
  },
  {
    id: "17",
    name: "Михаил Б.",
    city: "Москва",
    visa: "DTV 5 лет",
    date: "4 марта 2025",
    rating: 5,
    lang: "ru",
    text: "Фрилансер, доход в валюте. Проверили выписку и портфолио до подачи: сняли главный риск отказа.",
  },
  {
    id: "18",
    name: "Sophie M.",
    city: "London",
    visa: "Tourist visa",
    date: "21 February 2025",
    rating: 5,
    lang: "en",
    text: "Helping my parents in Russia. Communication in Telegram was fast; they got their visas before Songkran rush.",
  },
];
